// Thank you: https://github.com/aidenlx/media-extended/blob/main/esbuild.js
import esbuild from 'esbuild';
import fs from 'fs';
import process from 'process';
import builtins from 'builtin-modules';
import minify from 'css-minify';
import sass from 'sass'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Forked from kometenstaub/obsidian-version-history-diff
Source: https://github.com/capmaravilla/obsidian-version-render
Licensed under MIT
*/
`;

const cssBanner = `/*
Version Render - Obsidian Plugin
Licensed under MIT
*/
`;

const copyManifest = {
	name: 'copy-manifest',
	setup: (build) => {
		build.onEnd(() => {
			fs.copyFileSync('manifest.json', 'build/manifest.json');
		});
	},
};

const copyMinifiedCSS = {
	name: 'minify-css',
	setup: (build) => {
		build.onEnd(async () => {
		const {css} = sass.compile('src/styles.scss');
		const minCss = await minify(css);
		const content = `${cssBanner}\n${minCss}`;
		fs.writeFileSync('build/styles.css', content, {encoding: 'utf-8'});
		})
	}
}

const isProd = process.env.BUILD === 'production';

const context = await esbuild.context({
			entryPoints: ['src/main.ts'],
			bundle: true,
			//platform: 'browser',
			external: ['obsidian', 'electron', ...builtins],
			format: 'cjs',
			target: 'es2018',
			banner: { js: banner },
			sourcemap: isProd ? false : 'inline',
			minify: isProd,
			logLevel: 'info',
			treeShaking: true,
			define: {
				'process.env.NODE_ENV': JSON.stringify(process.env.BUILD),
			},
			outdir: 'build/',
			plugins: [copyManifest, copyMinifiedCSS],
			loader: { '.scss': 'text' }
		})

if (isProd) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}